### PR TITLE
Add simple script for s3 bucket

### LINKED ISSUE #38: Feature request: add a script to deploy on an AWS S3 bucket
Hello,

I would like to be able to deploy on an S3 bucket instead of a github page. Is it possible for you?

You can find a pull request https://github.com/storybooks/storybook-deployer/pull/37

Have a good day

### PR DESCRIPTION
**Pull request by jeanlucc**
closes #38

### CODE REVIEW

**Comment by jeanlucc** [comment]
@ndelangen Hello, here is a pull request to add a script that deploys to an AWS S3 bucket. Could you give me some insight on what needs to be done to achieve that?

**Comment by jeanlucc** [comment]
@gabrielcsapo Hello, could you give me some insight about this pull request? So that I can improve it and maybe merge it some day.
Regards

**Comment by hipstersmoothie** [comment]
@jeanlucc this seems reasonable to me. can you update it?

**Comment by hipstersmoothie** [comment]
Are you gonna re open this?

**Comment by jeanlucc** [comment]
Probably not, I need to redo everything because of the merged code and I do not need it so I won't waste my time.

**Pull request closed without merging**
