### PR TITLE
Add git default branch option

### PR DESCRIPTION
**Pull request by jsonunger**
It would be nice to support a default branch different from master. Please let me know if you'd like any modifications to this.

### CODE REVIEW

**Comment by shilman** [comment]
Awesome @jsonunger! What do you think about `source-branch` instead of `default-branch`?

**Comment by jsonunger** [comment]
@shilman `source-branch` works too. I picked `default-branch` since that's how Github catoregorizes the primary branch of a repo.

**Comment by shilman** [comment]
@jsonunger Yeah, I figured that. `source-branch` is more generic, and indicates that people can deploy from whatever branch they want (their non-master default branch, or even some other branch they've indicated. Of course, they could do the same with `default-branch`, but it seems less obvious to me.

**Comment by jsonunger** [comment]
@shilman I have updated the code to use a `source-branch` flag.

**Comment by shilman** [comment]
@jsonunger thanks for making this happen!!

**Pull request merged**
