### PR TITLE
Migrate to storybook

### PR DESCRIPTION
**Pull request by UsulPro**
@orta @ankurp @priley86 Thank you for the care of this project!

As we merge this PR we can publish as `@storybook/storybook-deployer` on npm

### CODE REVIEW

**Comment by shilman** [comment]
@UsulPro @ndelangen is there any reason why this isn't part of the monorepo?

**Comment by UsulPro** [comment]
@shilman I guess because it's the one small ES5 script without `dev` mode. 
It doesn't have any dependencies from main storybook monorepo and the monorepo doesn't depend on it

**Comment by UsulPro** [comment]
https://www.npmjs.com/package/@storybook/storybook-deployer

**Comment by shilman** [comment]
@UsulPro any reason why we didn't just call this `@storybook/deployer`?

**Comment by UsulPro** [comment]
@shilman I hesitated between the two options. And chose the most obvious for users. My point that it's a small project and has a small community possible not so active as Storybook's one. So I wanted them to spend less time thinking about migration. :) 
Perhaps it is not essential and better to use `@storyboook/deployer`?

**Comment by ndelangen** [comment]
Yes there's a reason this is not part of the monorepo. Part of it is lazyness on my part, but also this repo was moved into this organisation much later i think.

Last part and probably most significant: **I think this functionality should be part of the @storybook/cli. **

**Comment by UsulPro** [comment]
Norbert :+1:

**Comment by ankurp** [comment]
Keeping it part of monorepo while keeping a separate package from CLI would be good as the CLI would need to be installed globally and also locally and can lead to confusion if someone wants to publish from CI machines and also can lead to bloated node module if only they need is deployer and they get all other dependencies of CLI for functionality they do not need.

**Comment by priley86** [comment]
@UsulPro @shilman @ndelangen i've joined Storybook org, thanks so much!

I assume I can consume this from `@storybook/storybook-deployer` npm for now. Please just update the migration guide or let us know if it changes ;)

Will definitely continue to monitor this repo! 👍

**Pull request merged**
